<?php
 /**
  * Test array for the report class.
  **/  
  $test = array("0" =>array('title' =>'Laranjas (Oranges)',
                           'subtitle' =>'Green ones',
                           'valid' =>'2001-02-01',
                           'qtd' =>'100.0',
                           'total' =>'',
                           'duzia' =>'10.0'),
              "1" =>array('title' =>'Laranjas (Oranges)',
                           'subtitle' =>'Green ones',
                           'valid' =>'2001-02-02',
                           'qtd' =>'101.0',
                           'total' =>'',
                           'duzia' =>'11.0'),
              "2" =>array('title' =>'Laranjas (Oranges)',
                           'subtitle' =>'Yellow ones',
                           'valid' =>'2001-02-03',
                           'qtd' =>'102.0',
                           'total' =>'',
                           'duzia' =>'12.0'),
              "3" =>array('title' =>'Laranjas (Oranges)',
                           'subtitle' =>'Yellow ones',
                           'valid' =>'2002-12-03',
                           'qtd' =>'103.0',
                           'total' =>'',
                           'duzia' =>'22.0'),
              "4" =>array('title' =>'Laranjas (Oranges)',
                           'subtitle' =>'Golden ones',
                           'valid' =>'2001-12-03',
                           'qtd' =>'113.0',
                           'total' =>'',
                           'duzia' =>'3300'),
              "5" =>array('title' =>'Laranjas (Oranges)',
                           'subtitle' =>'Yellow ones',
                           'valid' =>'2001-12-03',
                           'qtd' =>'13.0',
                           'total' =>'',
                           'duzia' =>'300'),
              "6" =>array('title' =>'Café (Coffe)',
                           'subtitle' =>'Colombian',
                           'valid' =>'2001-12-13',
                           'qtd' =>'13.3',
                           'total' =>'',
                           'duzia' =>'30.1'),
              "7" =>array('title' =>'Café (Coffe)',
                           'subtitle' =>'Colombian',
                           'valid' =>'2001-12-12',
                           'qtd' =>'13.3',
                           'total' =>'',
                           'duzia' =>'35.1'),
              "8" =>array('title' =>'Café (Coffe)',
                           'subtitle' =>'Colombian',
                           'valid' =>'2001-10-13',
                           'qtd' =>'13.0',
                           'total' =>'',
                           'duzia' =>'3.1'),
              "9" =>array('title' =>'Café (Coffe)',
                           'subtitle' =>'Brazilian',
                           'valid' =>'2001-12-03',
                           'qtd' =>'1.3',
                           'total' =>'',
                           'duzia' =>'4.1'),
    );
?>
