<?php
 /**
  * Test array for the report class.
  **/  
  $test = array("0" =>array('store' =>'Main - Fifth Avenue',
                           'description' =>'Stuffones',
                           'valid' =>'2001-02-01',
                           'qtd' =>'100',
                           'value' =>'10.0'),
              "1" =>array('store' =>'Main - Fifth Avenue',
                           'description' =>'Stuffones',
                           'valid' =>'2001-02-02',
                           'qtd' =>'51',
                           'value' =>'11.0'),
              "2" =>array('store' =>'Main - Fifth Avenue',
                           'description' =>'Yellowones',
                           'valid' =>'2001-02-03',
                           'qtd' =>'22',
                           'value' =>'12.0'),
              "3" =>array('store' =>'Main - Fifth Avenue',
                           'description' =>'Yellowones',
                           'valid' =>'2002-12-03',
                           'qtd' =>'43',
                           'value' =>'22.0'),
              "4" =>array('store' =>'Main - Fifth Avenue',
                           'description' =>'Golden ones',
                           'valid' =>'2001-12-03',
                           'qtd' =>'32',
                           'value' =>'3300'),
              "5" =>array('store' =>'Main - Fifth Avenue',
                           'description' =>'Yellowones',
                           'valid' =>'2001-12-03',
                           'qtd' =>'13',
                           'value' =>'300'),
              "6" =>array('store' =>'Store 2',
                           'description' =>'Colombian coffe',
                           'valid' =>'2001-12-13',
                           'qtd' =>'13',
                           'value' =>'30.1'),
              "7" =>array('store' =>'Store 2',
                           'description' =>'Colombian coffe',
                           'valid' =>'2001-12-12',
                           'qtd' =>'3',
                           'value' =>'35.1'),
              "8" =>array('store' =>'Store 2',
                           'description' =>'Colombian coffe',
                           'valid' =>'2001-10-13',
                           'qtd' =>'6',
                           'value' =>'3.1'),
              "9" =>array('store' =>'Store 2',
                           'description' =>'Brazilian stuff',
                           'valid' =>'2001-12-03',
                           'qtd' =>'9',
                           'value' =>'4.1'),
    );
?>
